Add a readme.  Better usage info on zk subcommands.

diff --git a/solr b/solr
--- a/solr
+++ b/solr
@@ -17,7 +17,7 @@
 
 REQUIRED_PROGS=(which realpath lsof gzip mktemp)
 MINIMUM_JAVA_MAJOR_VERSION="11"
-JAR_FILE="solrcli.jar"
+JAR_FILE="build/libs/solrcli-all-0.0.1-SNAPSHOT.jar"
 LOG_FILE="solrcli.log"
 LOCAL_HEAP="128m"
 
@@ -153,8 +153,12 @@ function rotate_logs() {
   mv -f "${FULL_LOG_FILE}" "${FULL_LOG_FILE}.1" 2> /dev/null
 }
 
+#======================
+# Begin execution
+#======================
+
 TMPVARS=()
-SCRIPT_DIR="$(cd "$(dirname "$0")" || exit ; pwd -P)"
+SCRIPT_DIR="$(cd "$(dirname "$0")" || die "Error on cd to define SCRIPT_DIR" ; pwd -P)"
 cd "${SCRIPT_DIR}" || die "Can't cd to script directory ${SCRIPT_DIR}"
 
 find_java_home
@@ -162,18 +166,20 @@ check_required_progs
 assign_temp_file "TMPFILE1"
 
 # Run the application with options that do nothing and exit.
-# This is just to make sure that Java is new enough.
+# This is just to make sure that Java can run the program.
 "${JAVA_BIN}" "-Xmx${LOCAL_HEAP}" -jar "${JAR_FILE}" info --exit > "${TMPFILE1}" 2>&1
 RET="$?"
 UNSUPPORTED="$(grep -c "UnsupportedClassVersionError" "${TMPFILE1}")"
-
 if [ "${RET}" -ne 0 ]; then
+  {
+    echo "--- check command output:"
+    cat "${TMPFILE1}"
+    echo "---"
+  } >> /dev/stderr
   if [ "${UNSUPPORTED}" -gt 0 ]; then
-    log_err "Java not new enough.  Minimum major version is ${MINIMUM_JAVA_MAJOR_VERSION}."
+    log_err "Java not new enough.  Minimum major java version is ${MINIMUM_JAVA_MAJOR_VERSION}."
   fi
-  cp -f "${TMPFILE1}" /tmp/last_solr_error
-  log_err "Error encountered running the control program ${JAR_FILE}"
-  die "Output was placed in /tmp/last_solr_error"
+  die "Aborting due to error checking control program."
 fi
 
 # Run the application with an option to print the log directory and immediately exit.
@@ -187,8 +193,11 @@ FULL_LOG_FILE="${LOG_DIR}/${LOG_FILE}"
 rotate_logs
 
 # Run the application for real with all the options given to this script.
-"${JAVA_BIN}" "-Xmx${LOCAL_HEAP}" -jar "${JAR_FILE}" "$@" > "${FULL_LOG_FILE}" 2>&1
+# I was sending all output to a logfile, but that means the usage info
+# does not get displayed.  TODO: Need to plan out the log4j2 config.
+#"${JAVA_BIN}" "-Xmx${LOCAL_HEAP}" -jar "${JAR_FILE}" "$@" > "${FULL_LOG_FILE}" 2>&1
+"${JAVA_BIN}" "-Xmx${LOCAL_HEAP}" -jar "${JAR_FILE}" "$@"
 
-echo "JAVA_HOME=\"${JAVA_HOME}\""
-echo "JAVA_BIN=\"${JAVA_BIN}\""
+#echo "JAVA_HOME=\"${JAVA_HOME}\""
+#echo "JAVA_BIN=\"${JAVA_BIN}\""
 cleanup_and_exit
